### PR TITLE
[GH-1367] Fix dotween warnings

### LINKED ISSUE #1367: [REFACTOR] Fix DOTWEEN warnings
## 🚧 Refactor

All scripts using dotween need a refactor to prevent this warning:

Captura de pantalla 2024-01-29 a la(s) 10 58 07

This happens when the scene changes since dotween keeps running and the objects are no longer loaded

### Implementation

- Maybe using .Pause() .Complete() or .Kill() before the scene changes can prevent this from happening
- Add DOTWEEN to Title screen animations

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1367 
Solves 2 responsive issues similar to the ones in issue #1662 

## Motivation

We have in main a lot of warning logs regarding dotween:
Screenshot 2024-07-15 at 19 26 08

## Summary of changes

This PR:
- Adds a dotween handler to kill all tweens on every each scene change
- Deletes dotween calls when they weren't really needed
- Improves dotween implementations
- Fixes responsive issues in battle scene (settings button)

The only warning that should be left is the one triggered by the item pick up animation in `InventoryUI.cs`. This will be fixed in PR #1932. This is because the animation is changing and during the re-implementation the warnings will be taken into account
Screenshot 2024-07-17 at 19 40 28

[main]
Screenshot 2024-07-15 at 19 31 42

[this PR]
Screenshot 2024-07-15 at 19 35 02

- Fixes responsive issues in lobby scene (loading and cancel button)

[main]
Screenshot 2024-07-15 at 19 30 27

[this PR]
Screenshot 2024-07-15 at 19 33 52

## How has this been tested?

Use the game paying close attention to the console. No warnings regarding this issue should appear now.

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

File: client/Assets/Scripts/UI/TitleScreenController.cs [hunk 1]
```diff
@@ -11,65 +10,57 @@
...
     PlayerNameHandler playerNameHandler;
 
     [SerializeField]
-    CanvasGroup changeNameButton;
-
-    [SerializeField] CanvasGroup SingOutContainer, SingInContainer;
-
-    [SerializeField]
-    GameObject playerNamePopUp;
+    CanvasGroup logoImage, buttonsCanvas, singOutContainer, singInContainer;
```
Comment (tkz00) [inline client/Assets/Scripts/UI/TitleScreenController.cs:25]:
```suggestion
    CanvasGroup logoImage, buttonsCanvas, singOutContainer, signInContainer;
```

Since where at it.

**Review by tkz00 — CHANGES_REQUESTED** [review]
Screenshot 2024-07-16 at 4 49 19 PM

I get a lot of DOTween warnings when on the battle scene.

Also I wanted to ask if you had any insight on what tweens don't stop when changing scenes, where this ones causing some of the warnings? Was this why you had to add a script to kill all the tweens when changing scenes? Seems like pretty bad design from DOTween's part.

File: client/Assets/Scripts/UI/TitleScreenController.cs (hunk 1 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/TitleScreenController.cs]: Done!

**Review by tkz00 — CHANGES_REQUESTED** [review]
Screenshot 2024-07-18 at 2 51 32 PM

I got this DOTween warning that wasn't contemplated on the description of the PR, I didn't get what action triggered this, but at least it specifies which script caused it.

File: client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
Comment (tkz00) [inline client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab:1]: What are these changes? It has to do with the responsiveness of an element on the main screen?

File: client/Assets/Scripts/UI/TitleScreenController.cs [hunk 2]
```diff
@@ -11,65 +10,57 @@
...
+
     void Start()
     {
         avaibleCharactersNames = CharactersManager.Instance.GetAvailableCharactersNames();
-        StartCoroutine(FadeIn(logoImage.GetComponent<CanvasGroup>(), 1f, .1f));
-        StartCoroutine(FadeIn(ButtonsCanvas, .3f, 1.2f));
-        StartCoroutine(FadeIn(changeNameButton, 1f, 1.2f));
-        StartCoroutine(FadeIn(SingOutContainer, 1f, 1.2f));
-        StartCoroutine(FadeIn(SingInContainer, .3f, 1.2f));
+        Sequence titleDisplaySequence = DOTween.Sequence();
```
Comment (tkz00) [inline client/Assets/Scripts/UI/TitleScreenController.cs:41]: This animation differs from the current one in main, I don't know if this was intentional or not, let me know!

https://github.com/user-attachments/assets/fbeb390b-174d-43ba-8085-f4561e780167


https://github.com/user-attachments/assets/1905091a-716a-4992-ad14-2ee7741f2a26

File: client/Assets/Scripts/DamagePopUpAnimation.cs [hunk 3]
```diff
@@ -1,34 +1,53 @@
...
     public float moveY = 1.5f;
     public float moveX = 1f;
-    
+    private Coroutine popUpCoroutine;
+    private Tweener tweener;
+
     void Start()
     {
-        StartCoroutine(StartAnimation());
+        popUpRectTransform = GetComponent<RectTransform>();
```
Comment (tkz00) [inline client/Assets/Scripts/DamagePopUpAnimation.cs:16]: I believe this `GetComponent` call should be replaced by referencing the component in the prefab.

File: client/Assets/Scripts/DamagePopUpAnimation.cs [hunk 4]
```diff
@@ -1,34 +1,53 @@
...
     }
 
-    IEnumerator StartAnimation() {
-        // Get random tareget position
-        float[] targetsX = {-moveX, 0f, moveX};
-        System.Random random = new System.Random();
-        var indexX = random.Next(0, targetsX.Length);
+    IEnumerator StartAnimation()
+    {
+        if (GetComponent<RectTransform>())
```
Comment (tkz00) [inline client/Assets/Scripts/DamagePopUpAnimation.cs:22]:
```suggestion
        if (popUpRectTransform != null)
```

File: client/Assets/Scripts/UI/TitleScreenController.cs [hunk 5]
```diff
@@ -11,65 +10,57 @@
...
     PlayerNameHandler playerNameHandler;
 
     [SerializeField]
-    CanvasGroup changeNameButton;
-
-    [SerializeField] CanvasGroup SingOutContainer, SingInContainer;
-
-    [SerializeField]
-    GameObject playerNamePopUp;
+    CanvasGroup logoImage, buttonsCanvas, singOutContainer, signInContainer;
```
Comment (tkz00) [inline client/Assets/Scripts/UI/TitleScreenController.cs:25]:
```suggestion
    CanvasGroup logoImage, buttonsCanvas, signOutContainer, signInContainer;
```

File: client/Assets/Scripts/UI/TitleScreenController.cs (hunk 2 above)
Comment (AngieDutra) [reply client/Assets/Scripts/UI/TitleScreenController.cs:41]: You are right. I'll make it more similar to the one in main

File: client/Assets/Scripts/DamagePopUpAnimation.cs (hunk 4 above)
Comment (AngieDutra) [reply client/Assets/Scripts/DamagePopUpAnimation.cs:22]: Actually, I dont need this check. It was a debugging process for the warnings I forgot to delete

File: client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
Comment (AngieDutra) [reply client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab:1]: I was doing fixing a UX issue regarding the press animation for buttons but since the last merge to main I no longer need this

**Review by tkz00 — APPROVED** [review]
Great! Tested on my android!

**Review by ncontinanza — APPROVED** [review]
LGTM!
